// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {webrtc} from '../models';

export function GetCurrentOS():Promise<string>;

export function IsGamepadEnabled():Promise<boolean>;

export function IsKeyboardEnabled():Promise<boolean>;

export function NotifyCloseClient():Promise<void>;

export function NotifyCreateClient():Promise<void>;

export function OpenViGEmWizard():Promise<string>;

export function ToogleGamepad():Promise<void>;

export function ToogleKeyboard():Promise<void>;

export function TryClosePeerConnection():Promise<boolean>;

export function TryCreateHost(arg1:Array<webrtc.ICEServer>,arg2:string):Promise<string>;
