// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentOS() {
  return window['go']['bindings']['App']['GetCurrentOS']();
}

export function IsGamepadEnabled() {
  return window['go']['bindings']['App']['IsGamepadEnabled']();
}

export function IsKeyboardEnabled() {
  return window['go']['bindings']['App']['IsKeyboardEnabled']();
}

export function LogPrintln(arg1) {
  return window['go']['bindings']['App']['LogPrintln'](arg1);
}

export function NotifyCloseClient() {
  return window['go']['bindings']['App']['NotifyCloseClient']();
}

export function NotifyCreateClient() {
  return window['go']['bindings']['App']['NotifyCreateClient']();
}

export function OpenViGEmWizard() {
  return window['go']['bindings']['App']['OpenViGEmWizard']();
}

export function ToogleGamepad() {
  return window['go']['bindings']['App']['ToogleGamepad']();
}

export function ToogleKeyboard() {
  return window['go']['bindings']['App']['ToogleKeyboard']();
}

export function TryClosePeerConnection() {
  return window['go']['bindings']['App']['TryClosePeerConnection']();
}

export function TryCreateHost(arg1, arg2) {
  return window['go']['bindings']['App']['TryCreateHost'](arg1, arg2);
}
