// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';
import {bindings} from '../models';
import {webrtc} from '../models';

export function GetAudioProcess():Promise<Array<audio.AudioProcess>>;

export function GetCurrentOS():Promise<string>;

export function GetUsedPorts():Promise<bindings.UsedPorts>;

export function IsGamepadEnabled():Promise<boolean>;

export function IsKeyboardEnabled():Promise<boolean>;

export function IsMouseEnabled():Promise<boolean>;

export function IsWhipEnabled():Promise<boolean>;

export function LogPrintln(arg1:string):Promise<void>;

export function NotifyCloseClient():Promise<void>;

export function NotifyCreateClient():Promise<void>;

export function OpenViGEmWizard():Promise<string>;

export function SetAudioPid(arg1:number):Promise<void>;

export function ToogleGamepad():Promise<void>;

export function ToogleKeyboard():Promise<void>;

export function ToogleMouse():Promise<void>;

export function ToogleWhip():Promise<void>;

export function TryClosePeerConnection():Promise<boolean>;

export function TryCreateHost(arg1:Array<webrtc.ICEServer>,arg2:string):Promise<string>;
