version: '3'

tasks:
  build:
    cmds:
      - wails build -platform=windows/amd64,windows/arm64,linux/amd64,linux/arm64
  build-win:
    cmds:
      - wails build -platform=windows/amd64,windows/arm64
  build-linux:
    cmds:
      - wails build -platform=linux/amd64,linux/arm64

  dev-all:
    cmds:
      - wails dev

  dev-front:
    cmds:
      - cd frontend
      - pnpm run dev
  test:
    cmds:
      - cd frontend
      - pnpm run test