# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Fetch depth 0 is required for Changelog generation
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # ... do your compile, testing, bumpr, releasr steps here.
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build
        run: go build -v -ldflags="-H windowsgui -o ./RemoteController.exe"

      - name: Test
        run: go test -v ./...

      - name: Publish Release
        id: publish
        uses: packagrio/action-publishr-go@master
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        with:
          # upload any assets to your github release
          upload_assets: 'RemoteController.exe'