name: Wails build

on:
  push:
    tags:
      - '*' # Ejecuta en cualquier nuevo tag
permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: LibreRemotePlay-linux-amd64
            platform: linux/amd64
            os: ubuntu-latest
          - name: LibreRemotePlay-amd64.exe
            platform: windows/amd64
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Wails build
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          package: false
          go-version: 1.24.2
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files:
            build/bin/*